name: Running unit tests for my_lib

on:
  push:
    branch:
      - main
      
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main
      - name: Setup Python 3.9
        uses: action/setup-python@main
        with:
          python-version: 3.9
      - name: Run our unittest script
        run: python my_lib_testing.py